name: Auto Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: README generation
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install python3-yaml

      - name: Generate README
        run: ./scripts/generate_readme.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "[README] README Generated."
          commit_user_name: "Github Actions"
          commit_user_email: "actions@github"
